Repository thoth-station/s2i-tensorflow-gpu-notebook, pull requests merged in 2022-07, with the labels that each got.

#8 :arrow_up: Upgrade the tensorflow and other packages
  .s2i/bin/assemble
  Pipfile
  Pipfile.lock
  README.md
  requirements.in
Labels: approved, size/XXL

#9 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test

#11 :recycle: HouseKeeping: Updated OWNERS and pre-commit changes
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  OWNERS
Labels: approved, size/M

#13 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test

#16 :guardsman: Include version file for bot based release
  .github/CODEOWNERS
  thoth/s2i-tensorflow-gpu-notebook/__init__.py
Labels: size/S
